version: "3.5"

services:
    miiifu:
        build:
            context: ./docker
        expose:
            - 5000
        ports:
            - 5000:5000
        volumes:
            - ./services/web:/app:ro
