version: "3.5"

services:
    miiifu:
        build:
            context: services/miiifu
        expose:
            - 5000
        ports:
            - 5000:5000
        volumes:
            - ./services/miiifu:/app:ro
            # change this to actual data directory
            - ./test_data:/data
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        command: /venv/bin/gunicorn -k gevent --reload --workers 2 --worker-connections 5 --access-logfile=- --pythonpath /app -b :5000 miiifu:app

