path_prefix: /data
decompress_command: /usr/bin/grk_decompress
resolution:
    chain:
#        - type: base64
#        - type: url
#          prefix: https://example.org/
#        - type: json
#          key: path
           
